fp=open('index2.txt','w')
use_data='''id,first_name,last_name,email,gender
1,Jeffry,Cases,jcases0@buzzfeed.com,Agender
2,Justino,Dayment,jdayment1@nba.com,Male
3,Colas,Dixon,cdixon2@shared.com,Male
4,Adiana,Colwell,acolwell3@symantec.com,Polygender
5,Gipsy,Alty,galty4@surveymonkey.com,Female
6,Maurice,MacCallion,mmaccallion5@forbes.com,Polygender
7,Heidi,Norcock,hnorcock6@sourceforge.net,Female
8,Vinny,Bradnick,vbradnick7@yahoo.com,Female
9,Gaile,Ondrus,gondrus8@noaa.gov,Male
10,Rowland,Baack,rbaack9@macromedia.com,Male
11,Alvy,Silman,asilmana@cam.ac.uk,Male
12,Howie,Magne,hmagneb@wufoo.com,Male
13,Loralee,Marrill,lmarrillc@java.com,Female
14,Gail,Buckland,gbucklandd@tuttocitta.it,Female
15,Emily,Chasteney,echasteneye@blogs.com,Genderqueer
16,Emlyn,Ivoshin,eivoshinf@imageshack.us,Female
17,Stephine,Fairburne,sfairburneg@google.nl,Female'''
data=fp.write(use_data)
print(data)
fp.close()